### ISSUE TITLE
Plugin UIs expose bad layout, insufficiently display with OS-wide DPI scaling

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#117]
We have many plugins in JCT which have common problems: 
- High-DPI displays become more and more common and with them, OS-wide scaling of UI elements. In JCT, user interface elements of plugins often have fixed positions and bounding boxes. The operating system deals with High DPI by letting the user specify a scaling factor which influences the required size of the text of a control. The fixed element positions and bounding boxes clash with that.
- The plugin views and their controls responds badly to changes in the view size. Results in invisible texts due to cutoff or not expanding/shrinking a label or text field to its optimal size.
- In general, many plugins expose bad UI layout: buttons too small, crucial information not visible,e tc

This issue documents the plugins which expose these kind of problem and possible way to fix that. Of course, the problem could be fixed by manually refactoring all affected UI code one-by-one. With great static code analysis tools out there and the chance to kill many birds with one stone, some documentation may help to choose the right solution. 

Comments welcome about UI problems! Useful:
- Screenshots
- Plugin identification e. g. "Visualization -> Feige Fiat Shamir" or subproject ID
- What are the similarities between affected code
- What is needed for refactoring, ideas for best approach & automatisation

**Comment by simlei** [comment]
Visualizations -> Grille
================
<img width="319" alt="01_vis_grille" src="https://user-images.githubusercontent.com/982379/29490113-e79fe2c2-8532-11e7-8ea0-d0b6b9613eda.PNG">

**Comment by simlei** [comment]
Visualizations -> Hash Sensitivity
======
<img width="437" alt="02_vis_hashsensitivity" src="https://user-images.githubusercontent.com/982379/29490117-0e2d689c-8533-11e7-947b-db3524fe0b6c.PNG">

**Comment by simlei** [comment]
Visualizatons -> Inner states of DES
=====
 
<img width="439" alt="03_vis_innerstates_des" src="https://user-images.githubusercontent.com/982379/29490119-20b130ca-8533-11e7-9ea0-19918b1bc390.PNG">

**Comment by simlei** [comment]
Visualizations -> Merkle Hellman
=====
<img width="434" alt="04_merke_hellman" src="https://user-images.githubusercontent.com/982379/29490121-35d944a6-8533-11e7-8dc2-eb98f0b24efe.PNG">

**Comment by simlei** [comment]
Visualizations -> RSA cryptosystem
=======

<img width="433" alt="05_vis_rsa_vryptosystem" src="https://user-images.githubusercontent.com/982379/29490122-486bc53a-8533-11e7-898c-7adcf16b028a.PNG">

**Comment by simlei** [comment]
Visualizations -> SSL TLS Handshake
======
<img width="368" alt="06_vis_ssl_tls_handshake" src="https://user-images.githubusercontent.com/982379/29490124-5c8b7b5a-8533-11e7-890d-abda690a4d8c.PNG">

**Comment by simlei** [comment]
Visualizations -> Shamir secret sharing
=======

<img width="430" alt="07_vis_shamir_secret_sharing" src="https://user-images.githubusercontent.com/982379/29490128-70cab9c8-8533-11e7-93d6-d02e2080a9bc.PNG">

**Comment by simlei** [comment]
Visualizations -> Signature demonstration
=======
<img width="428" alt="08_vis_signature_demonstration" src="https://user-images.githubusercontent.com/982379/29490132-825b102a-8533-11e7-9f4e-a03735a4c685.PNG">

**Comment by simlei** [comment]
Games -> Numbershark
============

<img width="431" alt="09_games_numbershark" src="https://user-images.githubusercontent.com/982379/29490135-9483ef06-8533-11e7-8a8b-ad297e541fba.PNG">

**Comment by simlei** [comment]
Analysis -> Vigenére breaker
======

<img width="430" alt="10_analysis_vigenere" src="https://user-images.githubusercontent.com/982379/29490139-bfae5518-8533-11e7-88dc-47aca4fcc9af.PNG">

<img width="422" alt="10_analysis_vigenere2" src="https://user-images.githubusercontent.com/982379/29490142-d19d1458-8533-11e7-9059-38443e8d9918.PNG">

**Comment by simlei** [comment]
Visualizations -> Extended_RSA_cryptosystem
============

<img width="432" alt="11_vis_extended_rsa_cryptosystem" src="https://user-images.githubusercontent.com/982379/29490150-dcb95e00-8533-11e7-843a-9c9800cca369.PNG">

**Comment by simlei** [comment]
Visualizations -> Android Unlock Pattern
===========

<img width="430" alt="12_vis_aup" src="https://user-images.githubusercontent.com/982379/29490157-f48726de-8533-11e7-9520-b97e44f6d2e0.PNG">

**Comment by simlei** [comment]
Analysis -> Entropy analysis
===========

<img width="431" alt="13_vis_entropy_analysis" src="https://user-images.githubusercontent.com/982379/29490161-07021af8-8534-11e7-92f6-0bc0bdc7894a.PNG">

**Comment by Leikani** [comment]
# Visualizations -> Magic Door
<img width="831" alt="jct_magicdoor-window" src="https://user-images.githubusercontent.com/9982646/29999352-67e6f73c-9045-11e7-9644-88243cb05400.png">
<img width="233" alt="jct_magicdoor-dialog" src="https://user-images.githubusercontent.com/9982646/29999357-820e727a-9045-11e7-825c-2d223f2d3df0.png">

Here also, some parts cannot be read because not enough space reserved (cut-off texts). This happens both in the main windows as well as in the "Run-several-times" dialog.

[I made 2 screenshots but uploading with Firefox 55.0.2 caused the message: "Something went really wrong, and we can't process that file." Tried again with Chrome 60.0.3112.113, which worked.]

**Comment by simlei** [comment]
I suppose we all have this on the radar by now & for Release 1.0 we have already fixed much of that. I'm going to close this as it has seen thorough work on improving the situation. Until all of Eclipse GUI is vector based or SWT supports this natively, this may never get fully solved in any case for all platforms (Ubuntu 18.10 still has no proper DPI scaling for example).
