### ISSUE TITLE
Vigenère Breaker: English translation missing

### ISSUE THREAD

**Issue by dschadow** [jcryptool/crypto#18]
The Vigenère Breaker view is only available in German, English translation is missing (text and graphics).

**Comment by simlei** [comment]
I actually had that plugin programmed way better than it is now. Someone came along and integrated some plugins into it, changing layouts and messing everything up, including translations >:(. Needs more attention than this issue, and there is an effort incoming to fix all visualizations and plugins with such problems. Closing it to be reraised in some other form.
