### ISSUE TITLE
Classic crypto: Unification of pre-operation text filtering

### ISSUE THREAD

**Issue by dschadow** [jcryptool/crypto#2]
Two methods of text preprocessing before the cryptographic operation starts, exist: On the first wizard page of each algorithm the option is offered (and selected by standard) to filter characters from the input text that are not part of the plain text alphabet. if this option is not selected, non-alphabetic characters will occur unchanged at their original positions in the output. This text transformation is represented in the classic algorithm data object as a boolean. This method is an important part of the algorithm, because it guarantees, that only alphabetic characters are submitted to the algorithm engine.

The second method is part of the default pre-operation text transformations, which can be accessed from wizard page two of the classic algorithm wizards. It offers the functionality to filter the text by a specified alphabet or to leave it unchanged. This method is more "soft" than the first one, because it does neither interfere with the first method, nor is it meant to guarantee an "encryptability" of the text.

Several reasons exist, that the first method of filtering characters should be changed:
- Deselecting the first filtering option will impair the security of the output of nearly every algorithm, since plain text characters are revealed at their original positions
- algorithm configuration overload: For securing that a decryption does decrypt a text correctly, the user has to select the first filtering option the same way it was done at encryption, which complicates the process

Suggestion: try to remove this filtering option, and filter characters by default. Some related changes like a cipher text alphabet in addition to the plain text alphabet would be due, too.

**Comment by simlei** [comment]
Ciphertext alphabets may indeed be useful but in the context of the classic algorithms we almost never need them it seems to me. On the other hand, it would certainly come with increased complexity for the user.
I have thought about leaving out the filtering too. if there is consensus I can implement it.

**Comment by simlei** [comment]
I would like to close this old issue in favor of 1) issue tracker clean-up and 2) a hypothetical long-term, post-1.0 operation remodeling which should indeed target pre- and post processing of text. 

Not that this is the right place, but E4 migration seems like a good point to tackle some larger-scope remodeling stuff; as it stands, before 1.0 we would not remake working plug-ins, right?

**Comment by simlei** [comment]
Closed as of 1.0.0
