### ISSUE TITLE
Sudoku-Solver Job backgroundSolve causes StackOverflowError

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#205]
Starting a hexadecimal sudoku (switching from enter mode to solve mode) starts a job that calculates a solution for the sudoku in the background. This Job causes a StackOverflowError.

The user will be informed via an info dialog, which he can click away. He can then continue solving his sudoku.

**Comment by simlei** [comment]
SudokuSolver has not made it into v 1.0.0, so I have to close this.
