### ISSUE TITLE
Substitution analysis: Missing context help in DE and EN

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#214]

**Comment by grthor** [comment]
With commit https://github.com/jcryptool/crypto/commit/417f1bbc1d93ba0687c8b6d26ca4bc63178ffbe7 the necessary files for online and context help were created.

The german online help is located in: 
- org.jcryptool.analysis.substitution/nl/de/content/index.html

The english online help is located in:
- org.jcryptool.analysis.substitution/nl/en/content/index.html

The german context help is located in:
- org.jcryptool.analysis.substitution/nl/de/toc.xml

The english online help is located in:
- org.jcryptool.analysis.substitution/nl/de/toc.xml

**Comment by simlei** [comment]
From a quick glance, the context help seemed not to be available still. Investigate & close soon.
