### ISSUE TITLE
Frequency Analysis: Various changes

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#216]
The proposed changes are listed in the following PDF.
[FrequAnalyse-Todos.pdf](https://github.com/jcryptool/crypto/files/2985295/FrequAnalyse-Todos.pdf)

**Comment by grthor** [comment]
There was some work https://github.com/jcryptool/crypto/commit/6a088542afb29e9ee8dfb9e09378920cb118ba7d done in the last time, but it is not included in the last Weekly build, due to no weekly build was created last saturday.

Maybe @charlottemagister can state what changes have already been done.

**Comment by CharlotteMagister** [comment]
Hi,

I implemented points a-g of the Frequency Analysis section. I have **not** done:

h) Possibility for moving bars for mono alphabetic substitution.

i) Possibilities to add different n-grams.

I also did not do Part 2 as I only focused on the frequency analysis part.

Let me know if that was ok or if anything needs changed or added.

**Comment by grthor** [comment]
Great, good job @charlottemagister.

All must have points are done. Therefore, I will close the issue. For the remaining two points, I will open a new issue https://github.com/jcryptool/crypto/issues/264. This will have a lower priority, as the two points fit into the categories "Nice 2 Have" or "Feature Request".
