### ISSUE TITLE
ElGamal: Stepwise calculation does not work with keys > 32 bit.

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#218]
To reproduce the error, select a key with key length over 32 bit and press the start button in the group calculations.
The problem is caused by the switchable text boxes. These work on the basis of integers (32 bit) and can not convert longer text blocks than 32 bit.

The following exceptions are thrown
https://pastebin.com/xbkTm8Hu
https://pastebin.com/EW6egdxS

**Comment by simlei** [comment]
This issue won't be needing attention in the re-write of ElGamal, so this does not apply anymore (since 1.0.0, the original ElGamal plugin is not shipped with JCT anymore)
