### ISSUE TITLE
ElGamal: Make alphabet selectable (instead of fixed)

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#223]
It should be a smaller alphabet than the normal alphabet with 26 characters selectable. Many exercises use alphabets with fewer characters so that variables can be recalculated by hand.

That would allow the JCT to be used in IT security lectures.

**Comment by simlei** [comment]
@grthor @be4 What kinds of alphabets, for example?
I tried the El-Gamal visualization as well as the El-Gamal algorithm. None of them allowed selecting an alphabet whatsoever.

For sure, we have a mechanism for creating alphabets (in the preferences):
![image](https://user-images.githubusercontent.com/982379/66762554-81224780-eea6-11e9-8958-d0175e5e3521.png)

[1] contains the alphabets preference page as well as tools for including them into a plugin,
e.g. [2] 

[1] https://github.com/jcryptool/crypto/tree/develop/org.jcryptool.crypto.ui/src/org/jcryptool/crypto/ui/alphabets
[2] https://github.com/jcryptool/crypto/blob/develop/org.jcryptool.crypto.ui/src/org/jcryptool/crypto/ui/alphabets/AlphabetSelectorComposite.java

**Comment by simlei** [comment]
I propose this issue to not be handled until v1.0; however, the RSA and ElGamal plugins have serious issues and will receive in-depth attention anyway until version 1.0. Thus, if during that work adding alphabets seems feasible, why not.

**Comment by simlei** [comment]
This issue won't be needing attention in the re-write of ElGamal, so this does not apply anymore (since 1.0.0, the original ElGamal plugin is not shipped with JCT anymore)
