### ISSUE TITLE
As a general rule: The width of the images in the online help should be in percent

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#225]

**Comment by simlei** [comment]
I think this is an ideal candidate for a wiki page where we start to list plug-ins that do not meet this standard ("Non-issue parts"). One could automate this even.

**Comment by grthor** [comment]
I have added the information to the [wiki](https://github.com/jcryptool/core/wiki/Online-Help#screenshots).

With the following code you can specify the image width in %.

`<p align=center><img src="setup2.png" width="90%"></p>`

I will close the issue, as it has no place in the issue tracker.
