### ISSUE TITLE
Multipartite Key Exchange: Set values ​​in group "summary initial parameters" yourself

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#230]
It would be nice if you could set the values ​​in the group "Summary initial parameters" in the upper left corner by yourself.

<img width="966" alt="issue" src="https://user-images.githubusercontent.com/20046726/56863825-915b6e80-69bb-11e9-9475-7eb9966441ef.PNG">

**Comment by grthor** [comment]
@CharlotteMagister is currently working on it. 

This issue is closely related to https://github.com/jcryptool/crypto/issues/220.

**Comment by simlei** [comment]
As this is an improvement on a plugin that already works, but missing an implementation stub, this would be a new feature, now being tracked in https://github.com/jcryptool/core/wiki/Improvement-ideas-for-JCT-after-v1.0.0

**Comment by simlei** [comment]
Also, the upper left corner marked in the opening post is better located in the top right of the plugin, if no parameters can be set there (fits in better with the user workflow of other visualizations: displays should be at the right)
