### ISSUE TITLE
Visual plugin: Numbershark GUI changes and fixes

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#237]
In the .pdf are listed some recommended changes für the numbershark Plugin. The changes affect the GUI and the handlers, which can be seen in the top right corner of the plugin.

[Verbesserungsvorschläge.pdf](https://github.com/jcryptool/crypto/files/3493546/Verbesserungsvorschlage.pdf)

**Comment by simlei** [comment]
@grthor Have some or all of the points seen work since August?
I went ahead and re-assigned you but only because I got mixed up and was not sure whether you had already been assigned; it means nothing more than that.

**Comment by grthor** [comment]
@simlei i did not work on any of these points, so i will unassign myself. 
But will take a look on it the next days. It did not seem to much work (ca. 8h) and i already know the Plugin from previous work.
When I start working on it i will reassign myself.

**Comment by grthor** [comment]
I have already worked on this plugin and fixed some of the problems.

The next person working on this plugin should check if the problem is already fixed. Maybe its already done 😄

**Comment by grthor** [comment]
I have already worked on the plugin. So point no. 5 (not working forward and backward buttons) are fixed. All other problems are still open.

**Comment by simlei** [comment]
The improvement suggestions to number shark, in short:
 - new game button in the view, far right in the results box
 - a) Text: "und verwirft das bisher aktive Spiel."
 - new game dialogbox: Use more space for infos, e.g.
    - Zuletzt war Ihr Spielfeld <xx> Felder groß + Der Standard ist 20. Mit 40 Feldern ist es schon SEHR schwer + Sie können die Feldgröße zwischen 2 und 1024 variieren.
- 2 as minimum for game size
- Wenn man 2 Felder hatte und leider die 1 zuerst auswählte, ist die Empfehlung
(mit n<2 zustarten) falsch. Dieser Fall für n=2 muss extra behandelt werden: Am
besten nehmen Sie da einfach den Satz "Versuchen Sie es ... Zahlenvorrat."
weglassen.
- make dialogs resizable
- "7) Bitte das Interval der Werte für die Spielfeldgröße n hier noch mit ausgeben im
Beschreibungstext oben." -> @be4 , what was this point about? see linked pdf in first comment.
- include difference column in optimal/heuristic strategy viewer (player - shark)

**Comment by simlei** [comment]
- ensure that the dialogs have no critical errors on Windows (e.g. not show at all) @tassadarius

- Toolbar-half-star-Dialog:

```
>> 1) Unter Windows kommt folgender Dialog hoch.
>> 2) Ich klickte dann auf den 2. der drei Radiobutton im Dialog (van Nek).
>> Dann kam das ff. Ergebnis-Fenster.
>> Dabei habe ich ff. Probleme:
>> a) Das Fenster war schon initial sehr groß und ließ sich in der Größe
>> (Höhe) nicht ändern.
>> b) Im Dialog zuvor konnte man die "Größe der zu untersuchenden
>> Spielfelder" eingeben.
>>    Ich ließ es auf 39, also die Größen 2-40.
>>    Aber im Ergebnis-Fenster hier werden die Größen 2-250 ausgegeben.
>>    Wenn sich die "Größe der zu untersuchenden Spielfelder" nicht auf alle drei
>>    Radiobuttons bezieht, sollten wir es da ausblenden, wo es keinen Einfluss hat.
```

- still 250 instead of 519 optimal paths:

```
>> c) Warum ging es "nur" bis 250? Sie hatten ja schon von
>> vanNek optimale Werte bis 519 eingebaut, dann können wir 
>> die heuristischen Werte auch für höhere Werte berechnen oder.
```

- misc notes:

```
>> 3) Ich klickte dann auf den Vollstern (optimale Strategien).
>> Da werden die "Größe der zu untersuchenden Spielfelder" nur
>> eingeblendet, wenn man den 2. der beiden Radiobuttons klickt.
>> So sollte es auch sein.
```

**Comment by simlei** [comment]
- [x] half-star result dialog size changeable
- [x] heuristic calculations up to 519
- [x] heuristic calculations: respect max field size
- [x] optimal calculations / vanNek: respect max field size
- [x] calculation dialogs: select first radio button by default

**Comment by simlei** [comment]
~~1) Die Feldgröße der zu untersuchenden Spielfelder ist zu klein (sollte
mehr als 2 Stellen anzeigen können, mindestens 4).~~ edited by @grthor 
~~2) Das Icon "Zahlenhai frisst Restzahlen" ist disabled, obwohl 15 hat
keine freien Teiler mehr hat. **möglw. nach _undo_**~~

**Comment by grthor** [comment]
Fixed point 1 (Die Feldgröße der zu untersuchenden Spielfelder ist zu klein (sollte mehr als 2 Stellen anzeigen können, mindestens 4).) with https://github.com/jcryptool/crypto/commit/449c1e8b07eda3aed08d167765153a03c935a454.

**Comment by simlei** [comment]
Could not reproduce the issue with the disabled button:
```
2) Das Icon "Zahlenhai frisst Restzahlen" ist disabled, obwohl 15 hat
keine freien Teiler mehr hat. möglw. nach undo
```
The rest is fixed
