### ISSUE TITLE
Playfair

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#247]
A button that generates a sample key and inserts it directly in the "key" field would be nice.

For example, like this.
![feature request](https://user-images.githubusercontent.com/20046726/65158369-7c4aaf00-da32-11e9-8442-0ff00c436c9a.PNG)

**Comment by simlei** [comment]
As the classical algorithms (like Playfair) are controlled by a common dialog class, this is a change that would have to be made to all classical algorithms (which seems like a good idea!). It is tracked under "improvement ideas" in https://github.com/jcryptool/core/wiki/Improvement-ideas-for-JCT-after-v1.0.0

**Comment by simlei** [comment]
Generate button is not deemed necessary for classic algorithms anymore.
