### ISSUE TITLE
Animation in visual.ecdh (Diffie-Hellman Key Exchange) not working on Linux

### ISSUE THREAD

**Issue by tassadarius** [jcryptool/crypto#252]
On my Manjaro Linux the animation does not play at all.

System details:

- GTK+ 3.24.10
- OpenJDK Runtime Environment 1.8.0_222-b05

I already took a look and it seems Linux does not draw with a new GC which is initialized in `org.jcryptool.visual.ecdh/src/org/jcryptool/visual/ECDH/ui/view/Animation.java`. It only draws in a PaintListener where it can take the GC from the PaintEvent.

On Windows it seems to work fine, can't say if it works on MacOS

**Comment by grthor** [comment]
@tassadarius does the animation work now? If so, this issue could be closed. If not, you could give a short intermediate state of what's going on.

**Comment by grthor** [comment]
What is the current status here? If it is already fixed I would close the issue.

**Comment by tassadarius** [comment]
Not fixed yet and still persists

**Comment by simlei** [comment]
does only cause minor problems for the duration of the animation apparently
under linux, animation is not visible.
Plugin functionality in general is not affected.

**Comment by grthor** [comment]
I have now solved the problem by checking which operating system the user is using. If it is a Unix system I disable the animation. If it is another system (Windows, Mac), then the animation is enabled by default.

Since this "solves" the problem I close the issue.
