### ISSUE TITLE
Exception at start-up regarding AbstractEditorService

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#262]
Stacktrace that shows up on JCT start (from Eclipse PDE run configuration): https://pastebin.com/zmKLBT5H

It does not produce any directly visible error, however. Is anyone else seeing this?

**Comment by grthor** [comment]
@simlei i get exception too, in the WB and in Eclipse. 
The issue can only be a few days old, i didn't noticed the exception before.

**Comment by grthor** [comment]
Maybe this is related with https://github.com/jcryptool/core/issues/156. Since we switched back to Eclipse 2019-06 i did not get this exceptions on startup.

**Comment by simlei** [comment]
Have not had this problem ever since the switch back to 2019/06 in jcryptool/core/#156 and also not on my branch where it is fixed against 2019/09 . Therefore, I am closing it. Final Testing before v1.0 will include inspection of any start-up errors in the logs anyway.
