### ISSUE TITLE
Frequency Analysis: Monoalphabetic substitution and individual n-grams

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#264]
- It would be nice if you could use the Frequency Plugin for monoalphabetic substitution. This can be achieved if not all bars are moved, but only a few.
- After selecting the radio button "Add more complex analysis abilities" you should also be able to select your own n-grams.

These changes are just nice to have and have low priority. They are a relic of Issue https://github.com/jcryptool/crypto/issues/216.

For the implementation I would start taking a look at
https://github.com/jcryptool/crypto/blob/develop/org.jcryptool.analysis.freqanalysis/src/org/jcryptool/analysis/freqanalysis/ui/SimpleAnalysisUI.java 
and 
https://github.com/jcryptool/crypto/blob/develop/org.jcryptool.analysis.freqanalysis/src/org/jcryptool/analysis/freqanalysis/ui/FullAnalysisUI.java

**Comment by simlei** [comment]
Tracked with reference to this issue in https://github.com/jcryptool/core/wiki/Improvement-ideas-for-JCT-after-v1.0.0
