### ISSUE TITLE
Grille: 2. key input method / make grille rotation changeable

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#271]
### Key input method
For the grille visualization it would be nice if you could make the holes in the grille not only with mouse clicks, but also via a text field. The current key is only displayed in a text field. However, it cannot be changed via this text field. The text field should be extended so that the user can enter a key there.

As a starting point for solving this issues https://github.com/jcryptool/crypto/blob/66fa4c2ddd82b642a7bd3311a981f525a9ed150e/org.jcryptool.visual.grille/src/org/jcryptool/visual/grille/ui/View.java#L633-L636 can be used. The text field which only shows the current key is called keyText. This textfield you could extend.

###  Make grille rotation changeable
An other big improvement would be, if a user could select the rottation in which the grille is rotated during encryption/decryption. At the moment, the grille always turns clockwise.

There is no starting point for this problem as it is a completely new feature. The algorithm must also be adapted for this change, as it is only designed for clockwise rotations.

**Comment by simlei** [comment]
Fixed with v1.0.3: key input method and grille rotation are now fully provided.
