### ISSUE TITLE
Transposition Analysis: Various changes

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#273]
The plugin contains three more or less large problems. These are all described in detail in this PDF:
[JCT__Transposition_Turning-Grille (002) - gekürzt.pdf](https://github.com/jcryptool/crypto/files/3923460/JCT__Transposition_Turning-Grille.002.-.gekurzt.pdf)

In summary the second page of the text selection dialog is not displayed, the columns in the preview are not always wide enough and last but not least it would be nice if you could copy the key.

@simlei do you have time to take care of the problems? I saw in the git history, you programmed the plugin a few years ago.

**Comment by grthor** [comment]
@simlei @be4 I have a question about the blue link. Clicking on it opens a dialog where you can define your own alphabet. Does it have to be there? As far as I know, the definition of your own alphabet does not play a role in a transposition analysis.

Can I remove the link?

<img width="960" alt="Link" src="https://user-images.githubusercontent.com/20046726/71102243-7478e300-21b8-11ea-8eca-b282894727a2.PNG">

**Comment by grthor** [comment]
@simlei @be4 I investigated the missing second page of text load dialog. There was never content on this page since the initial commit 8 years ago.

Should i remove the page?

![image](https://user-images.githubusercontent.com/20046726/71103583-aa1ecb80-21ba-11ea-813b-5f464247f5b1.png)

**Comment by Leikani** [comment]
Da haben Sie bei den Transpositionschiffren recht.
Von mir aus braucht man den Link nicht.

@Leischnig: Einverstanden?

Gruß, BE


Am 18.12.2019 um 17:04 schrieb Thorben Groos:
> @simlei @be4 I have a question about the blue link. Clicking on it opens a dialog where you can define your own alphabet. Does it have to be there? As far as I know, the definition of your own alphabet does not play a role in a transposition analysis.
>
> Can I remove the link?
>
> <img width="960" alt="Link" src="https://user-images.githubusercontent.com/20046726/71102243-7478e300-21b8-11ea-8eca-b282894727a2.PNG">
>
>

**Comment by Leikani** [comment]
@Leischnig: Was war die Intention dahinter?

Gruß, BE

Am 18.12.2019 um 17:21 schrieb Thorben Groos:
> @simlei @be4 I investigated the missing second page of text load dialog. There was never content on this page since the initial commit 8 years ago.
>
> Should i remove the page?
>
> ![image](https://user-images.githubusercontent.com/20046726/71103583-aa1ecb80-21ba-11ea-813b-5f464247f5b1.png)
>
>

**Comment by simlei** [comment]
Ich habe keinerlei Erinnerung mehr an die Rationale; ich kann nur mutmaßen dass es das "neue Feature in Town" war und ich es vermehrt einsetzen wollte. Aber ich kann mir auch keinen rechten Reim drauf machen. 
Bin auch dafür, das raus zu nehmen. Zumal man beliebigen Editor-Inhalt auch per Menü (Edit -> ...) auf die exakt selbe Art vorbehandeln kann.

@grthor 
Danke für's Untersuchen!

**Comment by simlei** [comment]
Es hat mich doch nicht los gelassen weil der Dialog ja so gar keinen Sinn ergibt.. hab es mal komplett nachvollzogen:

1) Label mit diesem Text eingeführt 84b5738946862035de9686e9c69b69b7736b8fe7 (2012, simlei/moi)
2) Sinnloses OnClick-Event eingeführt: 362f3c80534de87e9b8468ff2bf541228ac11279 (simlei, auf einem Label, damals war es noch kein Link).
Message: "better dialog for creating new alphabets - not yet localized" (2012-08-16)
3) Label in einen Link geändert: 3508d242df0d763213f651092443356e9f4dbb25 (grthor, onClick Methode übernommen, nun durch Link-Form prominent) (2019)

So und nun die Pointe: Der Commit, wo ich diese offensichtlich zwecklose Alphabeteingabe eingeführt habe, beschäftigte sich so gut wie gar nicht mit der Transpositionsanalyse. Es war ein Update für... den Alphabeteingabe-Wizard.

Ich bin mir sicher, folgendes ist passiert: Ich war gerade fertig mit dem Transpositionsplugin und habe mich an den Alphabet-Wizard als nächste Aufgabe gemacht. Der hat keine eigene View -- ich brauchte einen Punkt in JCT auf den ich klicken konnte, um den neuen Alphabet-Wizard auszuprobieren. Ich nahm einfach irgendein Label in der letzten View die offen war (Tr.Analyse), machte die Alphabetfunktion fertig, und vergaß, den Click-Handler wieder vom Label herunter zu nehmen. 7 Jahre später findet ihn Hr. Groos und wundert sich warum der dort ist :1st_place_medal: -- zurecht ^^

Also ja. raus damit :)

**Comment by grthor** [comment]
So einen Ablauf kann ich mir auch gut vorstellen. Mal etwas ausprobiert und dann ist es ausversehen ins Repo gerutscht 😃 Schön, dass du es noch genau untersucht hast.

Gut dann hat sich das ja geklärt.

"Das neue Feature in Town" 😄 😄

**Comment by grthor** [comment]
Removed the link.
![Link entfernt](https://user-images.githubusercontent.com/20046726/71115571-84052580-21d2-11ea-9d8e-862e1ab387f2.PNG)

**Comment by grthor** [comment]
Removed 2. page of the input dialog.
![input dialog](https://user-images.githubusercontent.com/20046726/71116808-13abd380-21d5-11ea-9c8f-4bf88101c57f.PNG)

Damit sind die vorgeschlagenen Änderung für die Transpositionsanalyse alle umgesetzt. Ich würde den Issue dann schließen, wenn es keine anderen Anmerkungen mehr gibt.

**Comment by grthor** [comment]
There are two TODOs left, which I have not implemented. These should still be done:

1) In text input dialog there should be a way to remove delimiters between ciphertext blocks. For example to remove all spaces in the loaded text.
![eingabe](https://user-images.githubusercontent.com/20046726/71589004-b2b0c380-2b23-11ea-83cf-f56b8bb9aa4c.jpg)

2) If you press the buttons "colum-wise" or "row-wise" in the main window, the displayed permutation is always reset to the initial state. In the "Results" group, however, the manually set permutation is still displayed as the key. This should not be the case. Either the key should also be reset after a click on "colum-wise"/"row-wise" or the table should automatically be adapted to the changed input/output sequence. Then the key would not need to be reset.
![resetKey](https://user-images.githubusercontent.com/20046726/71589331-ce689980-2b24-11ea-8f34-6f80311ac566.PNG)

**Comment by simlei** [comment]
Fixed
