### ISSUE TITLE
Wrap-up for Milestone v1.0

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#284]
This issue gathers recently-closed issues that should be resolved, but for final testing, a compiled reference is useful. The goal is, for this to be the last issue for Milestone v1.0.0.

**Comment by simlei** [comment]
## Issues that should be resolved but may need some further testing

https://github.com/jcryptool/crypto/issues/266 - fixed
https://github.com/jcryptool/crypto/issues/213 - fixed
https://github.com/jcryptool/crypto/issues/44 - fixed
https://github.com/jcryptool/crypto/issues/279 - fixed
https://github.com/jcryptool/crypto/issues/273 - fixed
https://github.com/jcryptool/crypto/issues/51 - fixed
https://github.com/jcryptool/crypto/issues/167 - fixed

**Comment by simlei** [comment]
The issue that gathers combined testing & feedback for individual plugins with a view is here: 
https://github.com/jcryptool/crypto/issues/287

**Comment by grthor** [comment]
Since all issues listed in this issue have been resolved, I would suggest closing this "wrap-up"-issue for the sake of clarity.

**Comment by simlei** [comment]
fine by me. I'd suggest only to open such issues sparingly. e.g. the upcoming testing of the algorithm perspective. This way the tracker stays "flat".
