### ISSUE TITLE
ElGamal: Various improvements

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#288]
In the pdf are some problems and an issue in ElGamal listet.

[JCT-Feedback-before-Release_BE_v01_ElGamal.pdf](https://github.com/jcryptool/crypto/files/4368282/JCT-Feedback-before-Release_BE_v01_ElGamal.pdf)

**Comment by simlei** [comment]
Tracked as requirement document in the re-write of ElGamal (see: https://github.com/jcryptool/core/wiki/Improvement-ideas-for-JCT-after-v1.0.0)
