### ISSUE TITLE
Compound problems found while checking all crypto plugins

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#289]
In addition to https://github.com/jcryptool/crypto/issues/287, where all the single algorithms, games, visualization are checked, this issue serves to quickly note down problems that were found across all such plugins.

quite possible many of those have issues with overlap or even duplicates; the intent is to sort these out later when checking all crypto plugins is done. 

## Algorithm browser focus w.r.t. context help

If an algorithm, visual etc. registers context help, the algorithm browser loses focus on selection.
This causes problems e.g. when using the algorithm browser in "popped out" side window, as it disappears 
on focus loss. It is hardly ideal in normal view too, as multiple double clicks may be needed to 
open the desired view.

![algobrowser1](https://user-images.githubusercontent.com/982379/77776212-f39a7480-704d-11ea-966d-ee7547cc631b.gif)

## External links in online help do not work (Linux/GTK3)

- example: Signature-demo

**Comment by grthor** [comment]
Did you test on a JCT started out of eclipse or with an weekly build? The JCT started out of eclipse is sometimes a bit buggy.

**Comment by simlei** [comment]
I am testing on the latest weekly build

**Comment by simlei** [comment]
(moved)

**Comment by simlei** [comment]
## Scrolled composite

scrolling in views with the mouse pointer over an empty text field, or when there is no more scrolling in that direction to be had from the text field under the cursor, the scroll bar that overlooks the control does itself not scroll. In web browsers etc. this works as expected -- the scrolling is propagated upwards.

The only thing a user can do now is to find a spot for the mouse where nothing steals the scroll wheel input of the mouse which is not optimal.

**Comment by simlei** [comment]
All help-related issues are now tracked in https://github.com/jcryptool/crypto/issues/294
