### ISSUE TITLE
Visual plugin: test & fix Multipartite Key Exchange

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#299]
as this is not yet marked up with feedback in #287 @grthor

**Comment by grthor** [comment]
The plugin is tested superfically and works well so far.

The final test and fix will be done, after @be4 wrote the online-help. That will be in about 2 weeks.

**Comment by grthor** [comment]
@be4 wrote the online help and the plugin is reworked. So this should be closed within the next days.
@be4 will furthermore contact the initial plugin programmer and ask some questions about the mathematics behind the protocol. So there are maybe some changes incoming later.

**Comment by grthor** [comment]
The rework of the plugin is finished and @be4 finished the online help.
Therefore all mentioned points are finished and I will close this issue.
