### ISSUE TITLE
Visual plugin: Simple Power Analysis / Square and Multiply

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#304]
Simple Power Analysis / Square and Multiply (Übertrag)
Fix Plugin "Simple Power Analysis / Square and Multiply" according to #287 and https://github.com/jcryptool/crypto/issues/287#issuecomment-605456083 :

- **low/medium** UI is a bit rough on the edges and does not notify of insufficient input on subsequent iterations (I2). Nothing critical though.

**Textual:**
- Online help:
    - _"Ciphertext c(e.g. 5454)"_ (missing space)
    - "_copime_" --> "coprime"
    - "_Shown in the figure..._" --> "As shown in the figure..."
    - "_sub section_" --> "subsection"
    - "_, or graphs of electrical activity over time_" --> ", or graphs of electrical activity, over time"
    - `<\p>` artifacts in online help (e.g. at the end). The problem is with the backslash, it should be a slash.

**I1)**

![squaremulti1](https://user-images.githubusercontent.com/982379/77825223-3e78c280-7108-11ea-945b-8e2167285979.gif)

**I2)**

after executing with insufficient input, only a part of the usual results appears (empty input -> no op?), but nothing notifies the user of the limited value to be had from that result.

![squaremultiply2](https://user-images.githubusercontent.com/982379/77825231-420c4980-7108-11ea-9570-a747595b8d05.png)

**Comment by grthor** [comment]
All points addressed with https://github.com/jcryptool/crypto/commit/b745c4162a65dc24c4d06d840e6894dc80b7bfb7

```
Improvement of the SPA plugin. For more information see below: 
- Added example values
- Increased font size for titles
- Explanation text (bottom of the plugin) is resized correctly
- updated screenshots in online help
- added aditional label to explain the binary key d textfield
- fixed typos in online help
- input is checked and execute button is set accordingly
- removed tons of unused externalized strings.
```
