### ISSUE TITLE
Chinese Remainder Theorem

### ISSUE THREAD

**Issue by gknocke** [jcryptool/crypto#31]
This issue consists of some suggestions in order to improve the usability of "Chinese Remainder Theorem".

Important:
A "Reset" button is missing
The "Help" button in the "Verify Input" pop-up doesn't work

Nice to have:
The German translation in "Verify Input" is cutted after "Eingabe übernehmen mit dem Button". The text "<Übernehmen>." is missing
It is only possible to paste a one digit number

**Comment by simlei** [comment]
Layout problems partly still there (could be my high-DPI display though). We have a reset button by now.

Putting this together with a swath of other UI-related problems for coordinated effort.
