### ISSUE TITLE
Visual plugin: WOTS / WOTS+

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#310]
WOTS / WOTS+ visual plugin

- original test in https://github.com/jcryptool/crypto/issues/287#issuecomment-605451129

badly-scaled visual:

![wots1](https://user-images.githubusercontent.com/982379/77824246-95c76480-7101-11ea-80e1-dcdc9c359317.png)

**Comment by simlei** [comment]
While debugging something with TitleAndDescriptionComposite yesterday, I stumbled upon the reason for the WOTS visual error, so I'll fix it today.

**Comment by grthor** [comment]
Okay. I hadn't done anything with the plugin yet anyway.

I'm moving on to https://github.com/jcryptool/crypto/issues/308.
