### ISSUE TITLE
Data Encryption Standard: UI Changes

### ISSUE THREAD

**Issue by gknocke** [jcryptool/crypto#32]
This issue consists of some suggestions in order to improve the usability of "Data Encryption Standard".
1. The result of "Algorithm Study" is printed within the Input Box, "Fixed Point Study" prints the result below the output table and "S-Box Study" prints the result next to the output table. The outputs should be on the same position. For example in the bottom of the Output box. 
2. The results should be in a copyable form.

**Comment by simlei** [comment]
I remember having seen quite a few changes to that plug-in. UI seems to mirror the suggestions above. Will probably close after further review.

**Comment by grthor** [comment]
This feature request can be closed. All proposed changes have been implemented.
1. The results are displayed in all tabs to the right of the input group.
2. The result can be marked and copied with ctrl + c.
