### ISSUE TITLE
Make SHA version selectable

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#322]
As discussed on tuesday it would be nice, if a user could select which version is used. 

![image](https://user-images.githubusercontent.com/20046726/87692634-3ebacd80-c78c-11ea-8538-67142f7c9878.png)

One possibility to do this, is to add a dropdown (see screenshot) to the dialog which pops up after double clicking the "SHA" entry in the crypto explorer.

**Comment by grthor** [comment]
In the short term it would be nice if the SHA version could be recognized. The entry "SHA" should therefore be renamed to "SHA-2". (I think it was SHA-2.)

**Comment by grthor** [comment]
I renamed SHA to SHA-256 in https://github.com/jcryptool/core/commit/0e61fe3cadec7b44df503b2c05e2a80513d36ff6 to make it clear which SHA hash version is used. 

![image](https://user-images.githubusercontent.com/20046726/89211485-2e935280-d5c2-11ea-80c8-d39e2855d9af.png)

**Comment by simlei** [comment]
This dialog offers only SHA-256 as discussed. Nothing more remains to be done at this point.
