### ISSUE TITLE
Help TODOs

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#329]
The following help resources have TODOs inline:

- [ ] [core/org.jcryptool.core.help/nl/de/single/AES.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/de/single/AES.html)
- [ ] [core/org.jcryptool.core.help/nl/de/single/DSA.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/de/single/DSA.html)
- [ ] [core/org.jcryptool.core.help/nl/de/single/ElGamal.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/de/single/ElGamal.html)
- [ ] [core/org.jcryptool.core.help/nl/de/single/HMACMD5.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/de/single/HMACMD5.html)
- [ ] [core/org.jcryptool.core.help/nl/de/single/IDEA.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/de/single/IDEA.html)
- [ ] [core/org.jcryptool.core.help/nl/de/single/MD5.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/de/single/MD5.html)
- [ ] [core/org.jcryptool.core.help/nl/de/single/RC6.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/de/single/RC6.html)
- [ ] [core/org.jcryptool.core.help/nl/de/single/RNGSHA1.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/de/single/RNGSHA1.html)
- [ ] [core/org.jcryptool.core.help/nl/de/single/SHA256.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/de/single/SHA256.html)
- [ ] [core/org.jcryptool.core.help/nl/en/single/AES.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/en/single/AES.html)
- [ ] [core/org.jcryptool.core.help/nl/en/single/DSA.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/en/single/DSA.html)
- [ ] [core/org.jcryptool.core.help/nl/en/single/HMACMD5.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/en/single/HMACMD5.html)
- [ ] [core/org.jcryptool.core.help/nl/en/single/IDEA.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/en/single/IDEA.html)
- [ ] [core/org.jcryptool.core.help/nl/en/single/MD5.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/en/single/MD5.html)
- [ ] [core/org.jcryptool.core.help/nl/en/single/RC6.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/en/single/RC6.html)
- [ ] [core/org.jcryptool.core.help/nl/en/single/RNGSHA1.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/en/single/RNGSHA1.html)
- [ ] [core/org.jcryptool.core.help/nl/en/single/SHA256.html](https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.help/nl/en/single/SHA256.html)
- [ ] [crypto/org.jcryptool.visual.errorCorrectingCodes/nl/de/help/content/index.html](https://github.com/jcryptool/crypto/blob/develop/org.jcryptool.visual.errorCorrectingCodes/nl/de/help/content/index.html)
- [ ] [crypto/org.jcryptool.visual.errorCorrectingCodes/nl/en/help/content/index.html](https://github.com/jcryptool/crypto/blob/develop/org.jcryptool.visual.errorCorrectingCodes/nl/en/help/content/index.html)
- [ ] [crypto/org.jcryptool.visual.rainbow/nl/de/help/content/index.html](https://github.com/jcryptool/crypto/blob/develop/org.jcryptool.visual.rainbow/nl/de/help/content/index.html)

**Comment by grthor** [comment]
@be4 you worked on the online help files. Is this work done?

The error correcting codes online help is done by Frauenhofer institute.

**Comment by simlei** [comment]
Fixed with release of v1.0.0
