### ISSUE TITLE
Diffie-Hellman Key Exchange: UI Changes

### ISSUE THREAD

**Issue by gknocke** [jcryptool/crypto#33]
1. The domain parameters doesn't change if "c2tnb431r1" is chosen (Curve type F(2^m), Curve size Large).
   When a lagre curve size is activated, it is possible to insert zero or a negative number for Alice' and Bob's secret. This causes program errors.
2. The information pop-ups are very annoying. I suggest to add a description box in the excess space in the right instead.
3. The button "Choose random curve" changes its position while changing the curve size.
4. The value of G doesn't change when changing the curve size from large to small.
5. An open bracket is missing when large numbers are used (Public patrameters box --> Generator G).

**Comment by simlei** [comment]
Probably resolved by gknocke himself in Sep 2012: https://github.com/jcryptool/crypto/commit/25a9008371cceb9fbb58a27fff96631cb8643d48
