### ISSUE TITLE
ElGamal Cryptosystem: UI Changes

### ISSUE THREAD

**Issue by gknocke** [jcryptool/crypto#34]
1. Missing errorchecking: Key generation --> New key pair --> p
   p should be grater than 256, but a lower value doesn't deactivate the "continue" button.
2. When "Alice Whitehead" is used in the "Encrypt" tab, the output format is different: The hex values are not separated by spaces. This my be a problem if the user copies the text to another tab (e.g. "Decrypt) where the input values have to be seperated with spaces.
3. The input field in the Pop-up Decrypt --> "Enter Text" allows to insert multiple spaces in a row. Then, the input verification failes.
4. The Key "Alice Whitehead..Private Key" in "Encrypt" and "Sign" cannot be chosen. 
5. The input text in the "Decrypt" tab accepts lower case characters, which causes ArrayIndexOutOfBoundExeptions.
6. The text output in the calculations box is damaged in the german version.
7. The text input in "Verify" is damaged. The lines doesn't wrap and pasting in the second text box is also damaged
8. It is possible to export a (public) key (Encrypt, Verify) and import it to "Decrypt" or "Sign". This doesn't make sense as these computations need the private key and the result cannot be computed.
9. The Button "Key selection" in "Encrypt" an "Verify" cannot be pressed multiple times like in "Decrypt" or "Sign". 
10. The texoutput in the "Calculations" box should also be in a text field so that its output fits into the box.
11. During reset the "Step x from y" text should also be resetted
12. "Alice Whitehead..Public Key" causes problems in the step by step calculation. For some reason the program skips 2 steps.

**Comment by simlei** [comment]
Fixed much of this in https://github.com/jcryptool/crypto/commit/60113ae56bd2e9dcb96f1851cd66a12f2ff7ad4c
Probably needs reevaluation, but with this one I'm feeling quite confident.
