### ISSUE TITLE
Feige Fiat Shamir/Fiat Shamir: UI Changes

### ISSUE THREAD

**Issue by gknocke** [jcryptool/crypto#36]
This plugin needs basic changes to reach user-friendliness:

Input values:
A 10 digit number is not recognized as a correct value
The whole program freezes when choosing 2 as an input value
The output "n" is wrong, it prints just the first digit

Generate Primenumbers pop-up:
This pop-up has no headline
No input limitation in inputfields "Minimum level" and "Maximum level": The plug-in is not working when inserting -3 and -1, or 0 and 1 for example.
When using error pop-ups, a message like "Error.UPPER_LOWER" is not acceptable.
The Labels have to be improved, too. E.g. "Prime numberp" --> "Prime number p"
When choosing the option "Both equal" the labels "minimum level" and "maximum level" in the box Primenumberq the labels will be overwritten instead of the input fields
Some statements are inkorrekt: E.g. "sum of upper limits > 30" --> "Sum of upper limits >= 30", "The sum of the maximum levels must be less then 30" --> "The sum of the maximum levels exponents must be less than 30"

Basic layout:
(Feige Fiat Shamir only) The list "Amount of entries in a vector" is in a bad place, because it influences the steps above. This list belongs above "Action Flow"
The "Information" box should be positioned next to "Action Flow". There is no reason why these 4 buttons take that much space.
There are some senseless boxes as for example the box around the value n, or the box around the buttons.
The space between the elements and their content is not unified.

Run several times pop-up:
The Option "Alice knows the Secret" is useless, as the result is 100% independent from the amount of reruns.
The measured propability is clearly not correct. When the Amount of reruns is 1, the outout is "0 times right" in almost each run.
(Feige Fiat Shamir only) The "run several times" button should be disabled when clicking on "Reset"

**Comment by simlei** [comment]
Various persons have worked on this plugin since then, including myself, rohb, Holger Friedrich. Thus, this issue is probably outdated. 
Re-evaluation would be nice. If there are still ptoblems, we can put this either in a bundled "cosmetic efforts" documentation or make a new issue.
