### ISSUE TITLE
Doesn't open on MacOS 10.13.6

### ISSUE THREAD

**Issue by FigrHed** [jcryptool/crypto#361]
Error message says "“JCrypTool” is damaged and can’t be opened. You should move it to the Trash."

**Comment by simlei** [comment]
Hi, I'm sorry to hear it. Might these be the same symptoms as in https://github.com/jcryptool/core/issues/252?
We'll be sure to get this sorted out as soon as possible.

**Comment by FigrHed** [comment]
I don't know if its related to that issue but the error message is different (just updated initial comment)

**Comment by simlei** [comment]
Recent tests suggest that we linked a JRE that does not work under OSX. Could you try the following:
- Download and install this JRE: https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html
- Follow the other OSX-Instructions [on the download page](https://www.cryptool.org/en/jct/downloads), most importantly, the `sudo xattr -r -d [...]`

In our latest tests, the previously linked JRE was found to be the problem; this one (Amazon "Corretto") should work.

Thanks! :)

**Comment by FigrHed** [comment]
Thats done it!
I did not see those instructions as they are beneath the download button (so no reason to scroll down) and they are in a different box that is a different colour.
It would probably be better to put them above the download button *upside down smiley face)

**Comment by tassadarius** [comment]
@simlei @be4  Do we take any further actions from this? Should we adapt the website?

**Comment by simlei** [comment]
This is solved.
It can still kind of happen if you don't follow the instructions that are written everywhere you can download JCT though.
