### ISSUE TITLE
Homomorphic Encryption: UI Changes

### ISSUE THREAD

**Issue by gknocke** [jcryptool/crypto#39]
1. Gentry and Helevi --> First(Second) Operand: Cutting out the input values with "ctrl + x" causes this error: "Cut" did not complete normally.  Please see the log for more information.
   For input string: ""
2. Gentry and Helevi --> Modulus: The Headline of the Box is wrong. "Choose first operand" instead of "choose modulus" is printed.
3. RSA --> Key: The suggestion is missing
4. RSA --> Key: A warning appers if N is not the product of two prime numbers but the "Finish" button is still enabled
5. RSA --> Decrypt result: After prime numbers are inserted, the list for the exponents will be generated. Changing the window size  now destroyes the layout because the length of the drop down list changes

**Comment by simlei** [comment]
Probably fixed by cwfraemaekers already and some others: https://github.com/jcryptool/crypto/commits/develop/org.jcryptool.visual.he
Probably needs review before closing.

**Comment by tforneberg** [comment]
Can be closed, fixed the rest of these issues in #165.
