### ISSUE TITLE
Magic Door: UI Changes

### ISSUE THREAD

**Issue by gknocke** [jcryptool/crypto#41]
1. Placing the "Information" box next to "Action Flow" --- or at least above the buttons "Reset", "Rerun" and "Run several times" ---would improove the layout.
2. The descriptions are to less detailed. The user doesn't know what the algorithm is trying to archive.
3. If Alice is in the wrong room, she should change her position. But another click on "Change room?" causes a second room change. The picture doesn't change by changing the position twice, the description text will be wrong and Alice cannot be verified. Alice must not change the room twice.

**Comment by simlei** [comment]
Seems resolved by rohb up to his last commit https://github.com/jcryptool/crypto/commit/c39d0a06ca1b12623383b4c2eae42b5d80d8ef8b in 2013
