### ISSUE TITLE
Multipartite Key Exchange: UI Changes

### ISSUE THREAD

**Issue by gknocke** [jcryptool/crypto#42]
1. A reset button is missing
2. Broadcast PK(i) is not working, if Embedding degree k = 2 is chosen.
3. The description in "Step 3" is not helpful. A description what will be computed would be better. The formula should be written in a mathematical representation.
4. The "Details" box and the "Parameter summary" box consists of different notations: This should be unified
5. One Textfield for each value would increase the readability
6. The boxes "Definitions and notations" and "Details" should be swapped

**Comment by simlei** [comment]
gknocke worked on this: https://github.com/jcryptool/crypto/commit/ff7da0f64909335d031894a9835309f34ea4f8c2 

I could not reproduce any of these problems, there is a reset button, seems solved
