### ISSUE TITLE
Shamir's Secret Sharing: UI Changes

### ISSUE THREAD

**Issue by gknocke** [jcryptool/crypto#44]
1. Settings --> Coefficients: When all chosen coefficients are zero, a deadlock is reached.
2. Parameter box: The value p should be greater than n (p > n). That is incorrect. Is has to be (p > r) 
~~3. Parameter box: The last element of the polynome formula is ar x^r, which is wrong. It has to be a_r x^r~~
~~4. The lines "Graph" and "Settings" are not necessary and their labels are misleading.~~
~~5. No reset button~~
~~6. The "Select" button should be disabled when the values "p" and "s" are empty~~
~~7. The "Select all" and "Deselect all" buttons don't have good places. While using the graphic mode the buttons "Select all" and "Deselect all" controls the checkboxes on the other side of the window. These buttons have to be below the "Shares" box in both modes.~~
~~8. The "Reconstruct" button should be within the "Reconstruction" box, not within the "shares" box.~~
~~9. Reconstructon: If the numerical mode is used and the reconstruction failes the final message doesn't fit into its box. Also there is no reason why this message has a different position as the position in the graphical mode.~~

edited as of https://github.com/jcryptool/crypto/issues/44#issuecomment-363220464
--simlei

**Comment by simlei** [comment]
anatolibarski worked on this: https://github.com/jcryptool/crypto/commit/f38a2fe95daeb334d1bea68597f3bf2e1dbd9396

Would like to have reviewed before moving this issue

**Comment by tforneberg** [comment]
I addressed 3. - 9. in #139. 
1. and 2. might need further revision.

**Comment by simlei** [comment]
verify if deadlock == jct hangs

**Comment by simlei** [comment]
There is no deadlock anymore as far as I could reproduce it; the limit for p is now correctly observed.
