### ISSUE TITLE
Dragon Cipher: help outdated and only available in English

### ISSUE THREAD

**Issue by dschadow** [jcryptool/crypto#50]
The Dragon Cipher online help is completely outdated (especially the screenshots) and only available in English. There is no need to provide a screenshot showing how to launch the the wizard (first screenshot).

**Comment by simlei** [comment]
Seems solved to me:

![image](https://user-images.githubusercontent.com/982379/31457696-d621fa80-aebd-11e7-834f-743d6768b94a.png)
