### ISSUE TITLE
LFSR: help outdated and only available in English

### ISSUE THREAD

**Issue by dschadow** [jcryptool/crypto#51]
The LFSR online help is completely outdated (especially the screenshots) and only available in English.

**Comment by grthor** [comment]
Which Plugin is meant?

**Comment by grthor** [comment]
The GUI of the Plugin was reworked by me and afterwards @be4 revised the online help.

The problem is solved, the issue can be closed.

**Comment by simlei** [comment]
There are still TODOs, namely: https://github.com/jcryptool/crypto/blob/96cb06a00d2ca6b1e8ef66683d1fdd6dcc78bdaa/org.jcryptool.crypto.modern.stream.lfsr/nl/de/help/content/UI/tutorialUI.html#L35

Probably I am to blame for this not being done yet :P
attached are some screenshots from CT1 and txt files which document the inner states and outputs, HTH for now

[lfsr screenshots and txt](https://github.com/jcryptool/crypto/files/3772692/lfsrpics.zip)

**Comment by simlei** [comment]
There are no further TODOs marked down in the LFSR plug-in help.
