### ISSUE TITLE
Differential Power Analysis (Double and Add): Missing title area

### ISSUE THREAD

**Issue by dschadow** [jcryptool/crypto#75]
The view does not contain the JCrypTool default title and information area.

**Comment by simlei** [comment]
to be part of a consolidated effort

**Comment by simlei** [comment]
in explanation: this is how we like it:
![image](https://user-images.githubusercontent.com/982379/31458584-cc10631c-aec0-11e7-8180-55bcaa8bba26.png)

and this is the undesirable state of the plugin:
![image](https://user-images.githubusercontent.com/982379/31458599-dde66636-aec0-11e7-8fdf-5528f4907e8c.png)
