### ISSUE TITLE
Graph Isomorphism: Missing title area

### ISSUE THREAD

**Issue by dschadow** [jcryptool/crypto#79]
The view does not contain the JCrypTool default title and information area.

**Comment by hfriedr** [comment]
The Zero Knowledge plug-in already provided a useful class called ZKHeaderComposite that had only been used for providing a title area for the Magic Door scenario.  With two additional setter methods added, the ZKHeaderComposite class could also be used to provide a title area for the remaining scenarios of the Zero Knowledge plug-in, including Graph isomorphism.
