### ISSUE TITLE
Remove all deprecated usage in the JCTCA plug-in

### ISSUE THREAD

**Issue by dschadow** [jcryptool/crypto#96]
JCTCA plug-in uses a lot of deprecated classes (especially BouncyCastle), which sooner or later will stop working. Replace all deprecated classes with the correct ones.

One sample is the org.jcryptool.visual.jctca.Util class.

**Comment by simlei** [comment]
I have something in the making for Bouncycastle. I took a look at the Util class and I don't really feel like digging out all the deprecated methods if they still work. 

My opinion with Bouncycastle as it is now: If it ain't broke, let's not fix it. We'll throw out much of that code in the future anyhow.
