### ISSUE TITLE
Caesar chiffre should produce different cipher texts

### ISSUE THREAD

**Issue by dschadow** [jcryptool/crypto#99]
Using input ABCDEFGHIJKLMNOPQRSTUVWXYZ with key B should produce BCDEFGHIJKLMNOPQRSTUVWXYZA as alternative output and not only CDEFGHIJKLMNOPQRSTUVWXYZAB. The user should be able to select the desired behavior in the wizard (as in CrypTool).

**Comment by mouse07410** [comment]
In Caesar cipher "A" is supposed to mean "offset by one", not "offset by zero/none". Therefore key "B" enciphers "A" to "C".

**Comment by dschadow** [comment]
We need the same behavior/ possibilities as with CrypTool where the user can select the desired behavior.

**Comment by simlei** [comment]
fixed as of commit 613ab280af98a7cac89a570dd8b42d4f26e2394f. shift can be specified explicitely and when using a character-based key format, the interpretation of "A" can be set to shift = 0 or shift = 1.
